import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})
import Navigation from '@/components/Navigation'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <link rel="stylesheet" href="https://bootswatch.com/5/cyborg/bootstrap.css"/>
        </head>
        <body className={inter.className}>

        <Navigation/>
        <div className="container p-4">

            {children}
        </div>
        </body>
        </html>
    )
}
